### ISSUE TITLE
expose connect_timeout on HTTP remote

### ISSUE THREAD

**Issue by palenge** [iterative/dvc-http#15]
Hi! 
We have a HTTP remote, when we upload dig files we get connection timeout. There is any way to expose this property already exposed on S3?

**Comment by cklukas** [comment]
Please undo this change:
https://github.com/iterative/dvc-http/commit/c1cdbb3ef79a4705e6befbaa4537ea72059c3a2a#diff-81659e042f9d6ace20f56bc9182f71b64f14dcabb7f4a0dce2baa505d52383a6R121

This timeout means, that uploads need to finish in 60 seconds, causing major problems when using http remote to upload larger files. The timeout in our environment causes the upload to stop after 60 seconds, as until the upload is finished no response is send back to the client, causing a read-timeout. Please make remove this timeout, or make it possible, to set this through a setting on the dvc remote config, and/or through a environment variable.

**Comment by dtrifiro** [comment]
@cklukas Hi. That's not exactly how it works. `sock_read` sets the timeout for receiving data on the socket, meaning that if _no data_ is received for 60s, the socket is forcefully closed (e.g. see `aiohttp` docs here: https://docs.aiohttp.org/en/stable/client_quickstart.html#timeouts).

I do agree that there's some issue with timeouts and we'll be working to expose timeout options to avoid this kind of problems.
